language: node_js
node_js:
- 14
script: npm run test:unit
deploy:
  provider: s3
  access_key_id: AKIAYAXKG7IIGEUB3UUQ
  secret_access_key:
    secure: hH2RvV6KntRHK0o4SpVFX3HUTuFswSAPFXH89+o8SVTcuF4QE6MIn5E0yZatnOzfGmb4C2Ucus8OnW8iiyDf7ZmjSaoo/CFKIDc3A2KkHko4ZvmGPsfneYCxnpTuLGBGor8Uviy45xTVHDi5B4xsG2BK9VKFyDe13yhdhrib+zPE85oqTWSMWDP581Z4KUty3pI0w4e45aLN70Hfq8QPf/WTM9vW/sK/tjKjnkLrHE53snInxfGdI++azVzIC1e1hGqv0N29t4PJYfSM3dNHUvW7mVpWwLzDk77NEIQsb74dowxBMVQbvuVFBagWGBWddysFflnDG2yQ/Qm16d4Bln58Ca7HQB/h7YP8SN1krAy+6oA0qBmaU91OGmu8iEpPdSObs663pzLzQ626VaCLFzyMSN1WtNaj9ZpAKpkgWt0P90GvgAu90m5CAj328e0HO6pROKs05xwogC5OmpGRW0DH32+QbzyuYoKpqL8Sf3zBtAwxTBabrXtFmUe2QA0mnLSfghPU1jwT4m/hZeuo9PrTgs8Br4i9J5GXKGVHfn9HGs2i3jf0IzIWlWdUsI7H0Bv/BA1niCsJD+QWxR4J1sakjEdhw6kbeCwE1bZKv5leTJ6KASK3ObOCZatKz/xJ+uHovzu8aFxCt+VqfMsj1VEyH1tyEgY5C7KVN86inXE=
  bucket: cpg-code-editor-web
  acl: bucket_owner_full_control
  on:
    repo: casualbill/cpg-code-editor-web
  skip_cleanup: 'true'
