version: 2.1

orbs:
  node: circleci/node@4.1

jobs:
  lint-and-test:
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - node/install-packages
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test
          command: npm run test:unit

workflows:
  default:
    jobs:
      - lint-and-test
