const CODE_LANGUAGE_LIST = [
  { langName: 'C', langValue: 'c', langColor: '#B71C1C' },
  { langName: 'C++', langValue: 'cpp', langColor: '#880E4F' },
  { langName: 'C#', langValue: 'csharp', langColor: '#4A148C' },
  { langName: 'CSS', langValue: 'css', langColor: '#311B92' },
  { langName: 'Dart', langValue: 'dart', langColor: '#1A237E' },
  { langName: 'Go', langValue: 'go', langColor: '#0D47A1' },
  { langName: 'GraphQL', langValue: 'graphql', langColor: '#01579B' },
  { langName: 'HTML', langValue: 'html', langColor: '#006064' },
  { langName: 'Java', langValue: 'java', langColor: '#004D40' },
  { langName: 'Javascript', langValue: 'javascript', langColor: '#1B5E20' },
  { langName: 'JSON', langValue: 'json', langColor: '#33691E' },
  { langName: 'Lua', langValue: 'lua', langColor: '#827717' },
  { langName: 'Markdown', langValue: 'markdown', langColor: '#F57F17' },
  { langName: 'Objective-C', langValue: 'objective-c', langColor: '#FF6F00' },
  { langName: 'Pascal', langValue: 'pascal', langColor: '#E65100' },
  { langName: 'Perl', langValue: 'perl', langColor: '#BF360C' },
  { langName: 'PHP', langValue: 'php', langColor: '#3E2723' },
  { langName: 'Python', langValue: 'python', langColor: '#263238' },
  { langName: 'Redis', langValue: 'redis', langColor: '#FFD600' },
  { langName: 'Ruby', langValue: 'ruby', langColor: '#FFAB00' },
  { langName: 'SQL', langValue: 'sql', langColor: '#00C853' },
  { langName: 'Swift', langValue: 'swift', langColor: '#64DD17' },
  { langName: 'Visual Basic', langValue: 'vb', langColor: '#AEEA00' },
  { langName: 'XML', langValue: 'xml', langColor: '#00BFA5' },
];

export default CODE_LANGUAGE_LIST;
